[source]
wavelength = 1e-6             # Wavelength [m]
position = [1.0, 0.5]         # Position in MLA [spx]

[telescope]
diameter_ext = 6.5            # Primary mirror external diameter [m]
diameter_int = 1.3            # Primary mirror internal diameter [m]
# wfe = 'WFMap_Stack_Spectrograph.fits[idx]'  # WFE FITS file (default idx=0)
wfe = ''                      # WFE FITS file (default idx=0)
zernike = {7 = 2e-7}          # Zernike coefficients (Noll 1-index)

[telescope.support]
nsupport = 0                  # number of support arms
width = 0.15                  # width of support arms [m]
orientation = 0.349           # orientation of 1st support arm [rad]

[magnifier]
fratio = 555                  # f-ratio magnifier
# flength = d_tel * fratio_mag  # f magnifier [m]

[mla]
design = 'bigre'              # MLA optical design (bigre | tigre)

[mla.spaxel]
shape = 'square'              # µlens shape (square | hexagon)
orientation = 0               # µlens orientation [rad CCW from +x axis]
size = 700e-6                 # µlens size [m] (side)

[mla.tigre]
# One would set flength = fratio_mag * 2 * px_size.  Here we keep the f-length
# adapted to a spx scale of 40 mas (i.e fratio_mag = 555).
flength = 11.1e-3             # µlens f [m]

[mla.bigre]
# F-lengthes adapted to a spx scale of 40 mas (i.e fratio_mag = 555).
flength1 = 14.68e-3           # µlens f1 [m]
flength2 = 0.42e-3            # µlens f2 [m]

[diaphragm.tigre]             # Diaphragm for Tigre
shape = 'square'              # Slit diaphragm shape (circle | square)
size = 100e-6                 # Slit diaphragm size [m] (diameter | side)

[diaphragm.bigre]             # Diaphragm for Bigre
shape = 'square'              # Slit diaphragm shape (circle | square)
size = 30e-6                  # Slit diaphragm size [m] (diameter | side)

[spectrograph]                # Offner spectrograph (magnification=1)
# fratio = 8                    # f-ratio spectrograph (NOT USED)
flength = 250e-3              # Entry & exit focal lengths [m]

[spectrograph.m2]
shape = 'square'              # M2 shape (circle | square)
# size = f_spectro / fratio_spectro = 31.25e-3
size = 40e-3                  # M2 size [m] (diameter | side)

[detector]
px_size = 10e-6               # Pixel physical size [m]
