[tox]
envlist = py{310,311,312,313,314}{,-cov}
skip_missing_interpreters = True

[testenv]
description = run tests
extras =
    tests
package = wheel
wheel_build_env = .pkg
commands =
    pip freeze
    !cov: pytest --doctest-plus --durations=10 {posargs}
    cov: pytest --doctest-plus --cov slicersim --cov-report term {posargs}

; [testenv:docs]
; extras = docs
; usedevelop = true
; commands =
;     sphinx-build -nT -E --keep-going -b html docs/ docs/_build/html
