[source]
wavelength = 1e-6             # Wavelength [m]
position = [0.0, 0.5]         # Position in MLA [spx]

[telescope]
diameter_ext = 6.5            # Primary mirror external diameter [m]
diameter_int = 1.3            # Primary mirror internal diameter [m]
# wfe = 'WFMap_Stack_Spectrograph.fits[idx]'  # WFE FITS file (default idx=0)
wfe = ''                      # WFE FITS file (default idx=0)

[telescope.support]
nsupport = 0                  # number of support arms
width = 0.15                  # width of support arms [m]
orientation = 0.349           # orientation of 1st support arm [rad]

[magnifier]
fratio = 1587                 # f-ratio magnifier
# ×1/2 x-axis anamorphosis will be applied manually

[mla]
design = 'slicer'             # MLA optical design (bigre | tigre | slicer)

[mla.spaxel]
shape = 'rectangle'           # slice shape (square | hexagon | rectangle)
orientation = 0               # slice orientation [rad CCW from +x axis]
size = [25e-3, 1e-3]          # slice size [m] (side)

[mla.slicer]
flength1 = 300e-3             # slice f1 [m]
flength2 = 20.15e-3           # slice f2 [m]

[diaphragm.slicer]            # Diaphragm for Slicer
shape = 'rectangle'           # Slit diaphragm shape (circle | square | rectangle)
size = [2e-3, 0.5e-3]         # Slit diaphragm size [m]

[spectrograph]                # Spectrograph
flength1 = 723e-3             # Entry focal lengths [m]
flength2 = 361e-3             # Exit focal lengths [m]

[spectrograph.m2]
shape = 'rectangle'           # M2 shape (circle | square | rectangle)
# size = f_spectro / fratio_spectro = 31.25e-3
size = [26e-3, 90e-3]         # M2 size [m]

[detector]
px_size = 10e-6               # Pixel physical size [m]
