[scene.point_source]
name = "StdStar"
source = "GD71"            # Standard star name (CalSpec) *mandatory*
bandpass = "BessellV"      # Bandpass (sncosmo)
ABmag = 17.0               # AB magnitude in given bandpass *mandatory* (or nan)
reference = "gd71_mod_011.fits" # CalSpec file name (in CalSpec repo)
position = [1, 0.5]        # Position in MLA [spx] (to account for sub-px effect)

[scene.background]
name = "zodi"
model = "Aldering01.BB5800"  # Model [erg/cm²/s/Å/arcsec²] at North Ecliptic Pole
# See 2022A&A...662A.112E (Euclid prep. I)
scale = 2.0                  # Scaling factor (roughly 20° from ecliptic)
