[scene.point_source]
name = "SN Ia"
source = "salt2-extended"  # sncosmo model (flux in [erg/cm²/s/Å²])
redshift = 1.5
phase = 0                  # Phase of the target. 0 means at max for SN Ia.
MBmax = -19.3              # Peak absolute AB-mag in Bessel B
position = [1, 0.5]        # Position in MLA [spx] (to account for sub-px effect)
c = 0                      # SN Ia SALT2 color
x1 = 0	                   # SN Ia SALT2 stretch

[scene.background]
name = "zodi"
model = "Aldering01.BB5800"  # Model [erg/cm²/s/Å/arcsec²] at North Ecliptic Pole
# See 2022A&A...662A.112E (Euclid prep. I)
scale = 2.0                  # Scaling factor (roughly 20° from ecliptic)
