"""
Top-level tool to interact with SNR simulation.

.. autosummary::

   Study
   StudyCase
   StudySample
"""

import warnings
import numpy as np
import pandas

try:
    from tqdm.auto import tqdm
except ModuleNotFoundError:
    tqdm = lambda arg, **kwargs: arg

from .simulation import Simulation


def mesh_kwargs(**kwargs):
    """
    Create a dataframe with all parameter combinations.

    >>> mesh_kwargs(scale=[0.02, 0.05], sigma=[0.03, 0.06])
       scale  sigma
    0   0.02   0.03
    1   0.05   0.03
    2   0.02   0.06
    3   0.05   0.06
    """

    scan_params = list(kwargs.keys())     # (npar,)
    # Number of scanned parameters (i.e. columns in final df)
    # npar = len(scan_params)

    mesh = np.meshgrid(*kwargs.values())  # npar × (nval1, nval2, ...)
    mshape = np.shape(mesh)               # (npar, nval1, nval2, ...)
    shape = (mshape[0], np.prod(mshape[1:]))  # (npar, nval1*nval2*...)
    df_params = pandas.DataFrame(
        np.reshape(mesh, shape).T,        # (nval1*nval2*..., npar)
        columns=scan_params)              # (npar,)

    return df_params


def get_sneia_simulation(size=10_000, zmax=1.5, **kwargs):
    """
    Get a dataframe of simulated Type Ia Supernovae (Tripp relation only)

    :param int size: number of simulated targets
    :param float zmax: maximal redshift
    :param kwargs: goes to SNeIa.from_draw (zmin, etc)
    :return: dataframe
    """

    from skysurvey import target

    sneia = target.SNeIa.from_draw(size=size, zmax=zmax, **kwargs)

    return sneia.data.copy()


def show_timescan(data,
                  ax=None, ystep=1, total_time=3,
                  rename_param={}, **kwargs):
    """
    Display the dataframe created by scan_totaltime

    :param pandas.DataFrame data: dataframe generated by
           :meth:`StudySample.scan_totaltime`
    :param ax: matplolib's axes
    :param float ystep: vertical offset between bars
    :param float total_time: total time (in year) of the mission
    :param dict rename_param: change the scanned parameter names.
    :param kwargs: goes to ax.barh
    :return: figure
    """

    from astropy import units
    from matplotlib.colors import to_rgba
    import matplotlib.pyplot as plt

    if ax is None:
        fig = plt.figure(figsize=[7, 4])
        ax = fig.add_axes([0.15, 0.2, 0.7, 0.7])
    else:
        fig = ax.figure

    ylabels = []
    yarray = []

#    data = data.copy().reset_index()
    for i, (index, data_) in enumerate(data.iterrows()):
        y = i*ystep
        yarray.append(y) # for set_yticks later on
        data_param = data_[data_.index[~data_.index.isin(["targets","targets_main","targets_overhead"])]
                          ].rename(rename_param)

        ylabels.append("\n".join([f"{k}:{v}" for k,v in data_param.iteritems()]))


        ax.barh(y, total_time, facecolor="None", edgecolor="0.7", zorder=5,
               **kwargs)
        ax.barh(y, total_time*0.75, facecolor="None", edgecolor="k", zorder=5,
               **kwargs)

        # data
        on_targets = data_["targets"] * units.second.to("year")
        target_main = data_["targets_main"] * units.second.to("year")
        overhead = data_["targets_overhead"]* units.second.to("year")-on_targets
        targets_top5 = on_targets - target_main

        # data main
        ax.barh(y, target_main, left=0,
                facecolor=to_rgba("C0",0.8), edgecolor=None,  zorder=3,
                label="main targets" if i==0 else "",
               **kwargs)
        # data to 5%
        ax.barh(y, targets_top5, left=target_main,
                facecolor=to_rgba("C0",1), edgecolor=None,  zorder=3,
                label="5% faintest" if i==0 else "",
               **kwargs)

        # data overhead
        ax.barh(y, overhead, left=on_targets,
                facecolor="tab:grey", edgecolor="k", zorder=3,
                label="overhead" if i==0 else "",
               **kwargs)

    clearwhich = ["left","right","top","bottom"]
    [ax.spines[which].set_visible(False) for which in clearwhich]
    ax.set_xticks([1,2,3])
    ax.set_yticks(yarray, labels=ylabels, fontsize="x-small")

    ax.legend(bbox_to_anchor=(0., 1.0, total_time/(total_time+0.1), .10), loc='lower left',
                              ncol=3, mode="expand",
            borderaxespad=0., fontsize="x-small", frameon=False)

    ax.set_xlim(0,total_time+0.1)
    ax.set_xlabel("Mission Time (yr)")
    return fig


class Study:
    """
    Explore MLAperf simulations.

    .. seealso::

       * :class:`StudyCase`: study single case
       * :class:`StudySample`: study samples
    """

    def __init__(self, simu):
        """
        Study a :class:`Simulation`.

        :param Simulation simu: simulation to be explored.
        """

        self.simu = simu

    @classmethod
    def from_config(cls, config):
        """
        Load the simulation given its config.

        This calls `Simulation.from_config(config)`.

        :param dict config: top level configuration containing
                            configurations for scene, spectrograph, detector
                            and extraction parameters (by default:
                            use default config from
                            :func:`mlaperf.iotools.get_config`)
        :return: scene instance
        """

        simu = Simulation.from_config(config)
        return cls(simu=simu)

    def update_simulation(self, **kwargs):
        """
        updates the simulation and returns the original config.
        """

        changed_parameters = list(kwargs.keys())
        if "abmag" in changed_parameters:
            changed_parameters[changed_parameters.index("abmag")] = "redshift"

        origin = self.simu.get_parameter( changed_parameters ) # origin parameters
        self.simu.update(**kwargs) # set the new config

        return origin

    def fetch_nramp(self, target_snr, lbda_range=[4000, 6800], frame="rest", statistic=np.nanmean,
                        min_ramps=1, max_ramps=50, **kwargs):
        """
        loop over the number of ramps to get the first that passes the target_snr.

        unlike reach_snr, this does not fit, but loops over the number of ramps.

        :param float target_snr: objective SNR
        :param lbda_range: (wmin, wmax) test wavelength range [Å] (or list of)
        :param str frame: wavelength frame ('obs' or 'rest')
        :param statistic: numpy function to apply on test domain
        :param int min_ramps: minimal number of ramp
        :param int max_ramps: maximal number of ramp
        :param kwargs: goes to update_simulation to locally change the simulation parameters.
        :return int: minimal number of ramps needed to reach the target snr

        """

        nramp_orig = self.simu.get_parameter( "nramp" )
        origin = self.update_simulation(**kwargs)

        nramp_ = max_ramps
        for nramp in np.arange(min_ramps, max_ramps+1):
            # Compute SNR
            self.simu.update(nramp=nramp)
            snr = self.simu.get_band_snr( lbda_range=lbda_range, frame=frame, statistic=statistic)
            if snr>=target_snr:
                nramp_ = nramp
                break

        self.simu.update(nramp=nramp_orig)
        self.simu.update(**origin) # set back origin
        return nramp_

    def reach_snr(self, target, free_param="nramp",
                      lbda_range=[4000, 6800], frame="rest", statistic=np.nanmean,
                      as_int=False, reset_param=True, bounds=None):
        """
        Optimize parameter to reach target SNR.

        :param float target_snr: objective SNR
        :param str free_param: name of the mutable parameter to be optimized
        :param lbda_range: (wmin, wmax) test wavelength range [Å] (or list of)
        :param str frame: wavelength frame ('obs' or 'rest')
        :param statistic: numpy function to apply on test domain
        :param bool as_int: get the fitted variable as an int (ceil)
        :param bool reset_param: reset the optimized parameter to its input value
        :param bounds: boundaries of the optimized parameters (e.g. `[0, None]`)
        """

        from iminuit import Minuit

        def _objfun(value):                     # Objective function
            self.simu.update(**{free_param: value})  # Update simulation
            snr = self.simu.get_band_snr(            # Compute SNR
                lbda_range=lbda_range, frame=frame, statistic=statistic)
            return (snr - target)**2

        input_param = self.simu.get_parameter(free_param)
        init_param = 2#

        m = Minuit(_objfun, value=init_param)

        # Boundaries, mostly to avoid negative ngroup / nramp
        if free_param in ["ngroup", "nramp"]:
            as_int = True
            if bounds is None:
                bounds = [1, None]

        if bounds is not None:
            m.limits["value"] = bounds

        m.migrad()              # Minimization
        if not m.valid:
            print(m)
            warnings.warn(f"Cannot reach target SNR by varying parameter {free_param!r}.")

        value = m.values["value"]
        if as_int:
            value = np.ceil(value).astype(int)

        if reset_param:         # Reset if needed
            self.simu.update(**{free_param: input_param})

        return value

    def plot_psfsize(self, guiding_psf=(0, 0.01, 0.02, 0.05), ax=None):
        """
        Plot total spatial PSF scale given diffraction and guiding errors.

        :param guiding_psf: list of guiding error (sigma) [arcsec]
        """

        import matplotlib.pyplot as plt
        from astropy import units as u

        lbda = self.simu.spectrograph.lbda * u.angstrom
        sigma = self.simu.spectrograph.get_spatial_sigma() * u.arcsec
        dext = self.simu.spectrograph.meta["mirror"]["diameter_ext"]

        if ax is None:
            fig, ax = plt.subplots()

        for sguiding in guiding_psf:
            ax.plot(lbda.to(u.um),
                    np.hypot(sigma.to(u.arcsec), sguiding * u.arcsec) * 1e3,
                    label=f"{sguiding}\"", ls="--")

        # baseline
        sguiding = self.simu.get_parameter("guiding_sigma")
        ax.plot(lbda.to(u.um), np.hypot(sigma.to(u.arcsec), sguiding * u.arcsec) * 1e3,
                label=f"baseline\n{sguiding}\"", ls="-", color="k")

        spaxel_scale = self.simu.get_parameter("spatial_scale") * 1e3  # [mas]
        ax.axhline(spaxel_scale, ls="-", zorder=1, color="0.6")
        ax.set(xlabel="Wavelength [µm]",
               ylabel="σ (optics + guiding) [mas]",
               title=f"Total PSF for a {dext} telescope")
        ax.grid()
        ax.legend(title="Guiding error")

        return ax


class StudyCase(Study):

    def scan_variance(self, target_snr=10, free_param="nramp",
                      lbda_range=[4000, 6800], frame="rest",
                      statistic=np.nanmean,
                      **kwargs):
        """
        Scan variance origin over mutable parameters for a given SNR.

        :param float target_snr: objective SNR
        :param str free_param: name of the mutable parameter to be optimized
        :param lbda_range: (wmin, wmax) test wavelength range [Å] (or list of)
        :param str frame: wavelength frame ('obs' or 'rest')
        :param statistic: numpy function to apply on test domain
        :param dict kwargs: dictionary for test parameters
                            (e.g. `redshift=[0.5, 1.0, 1.5]`)
        :return: resulting dataframe
        :rtype: pandas.DataFrame
        """

        df_params = mesh_kwargs(**kwargs)

        # SNR properties
        snr_prop = dict(lbda_range=lbda_range, frame=frame, statistic=statistic)

        # Loop over parameter sets
        subdfs = []
        for _, params in tqdm(df_params.iterrows(), total=df_params.shape[0]):
            # For each row, update the npar parameters...
            param_dict = params.to_dict()
            self.simu.update(**param_dict)
            # Get the value of free parameter that provides the target SNR
            param_snr = self.reach_snr(
                target_snr, free_param=free_param, as_int=True, reset_param=True,
                **snr_prop)
            # Update the parameter accordingly
            self.simu.update(**{free_param: param_snr})

            dict_variances = self.simu.estimate_variance_contribution(**snr_prop)
            dict_variances[free_param] = param_snr

            subdf = pandas.Series(dict_variances)
            subdfs.append(subdf)

        df_variances = pandas.concat(subdfs, axis=1).T
        return df_params.join(df_variances)

    def scan_snr(self, lbda_ranges=[4000, 6800], frame="rest",
                     statistic=np.nanmean, name_ranges=[],
                     **kwargs):
        """
        Scan SNR over mutable parameters and store stats in dataframe.

        :param list lbda_ranges: list of (wmin,wmax) wavelength domains [Å]
        :param str frame: wavelength frame ('obs' or 'rest')
        :param statistic: numpy function to apply on test domains
        :param list name_ranges: names of wavelength domains
                                 ('wmin-wmax' by default)
        :param dict kwargs: dictionary for test parameters
                            (e.g. `redshift=[0.5, 1.0, 1.5]`)
        :return: result dataframe
        :rtype: pandas.DataFrame
        """

        lbda_ranges = np.atleast_2d(lbda_ranges)
        assert lbda_ranges.ndim == 2 and lbda_ranges.shape[-1] == 2, \
            f"Invalid lbda_ranges {lbda_ranges!r}."
        # Number of spectral bands
        nband = len(lbda_ranges)

        if not name_ranges:     # ['wmin_wmax'] by default
            name_ranges = [ f"{wmin:.0f}-{wmax:.0f}"
                            for wmin, wmax in lbda_ranges ]

        df_params = mesh_kwargs(**kwargs)
        print(f"SNR scan: {nband} bands, {npar} parameters, {nvalue} rows")

        subdfs = []
        # Loop over parameter sets
        for _, params in tqdm(df_params.iterrows(), total=df_params.shape[0]):
            # For each row, update the npar parameters...
            param_dict = params.to_dict()
            self.simu.update(**param_dict)
            # ... simulate and get the variance and signal...
            sig, var = self.simu.get_band_signal(
                lbda_ranges, frame=frame, statistic=statistic)
            # ... and store in results
            subdf = pandas.DataFrame({**{"signal": sig,
                                         "variance": var,
                                         "SNR": sig / var**0.5,
                                         "band": name_ranges},
                                      **param_dict})
            subdfs.append(subdf)

        df = pandas.concat(subdfs).reset_index(drop=True)
        df.attrs = self.simu.meta    # Add meta-data

        return df

    def fetch_maglimit(self, precision=0.1, magrange=[10,20], nmd=None):
        """
        fetch the smallest magnitude that has no saturation pixel

        :param float precision: step between two scanned magnitudes
        :param magrange: range of magnitude to be scanned.
        :param tuple nmd: detector NMD parameters

        :return float: minimal magnitude that does not saturated
        """

        mags = np.arange(*magrange, precision)
        origin_mag = self.simu.get_parameter("ABmag")
        if nmd is not None:
            origin_nmd = self.simu.get_parameter("nmd")
            self.simu.update(nmd=nmd)

        # scan over the magnitude limits

        mag_sat = None
        for mag in mags:
            self.simu.update(ABmag=mag)
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                data, _ = self.simu.get_detected_cube() # variance ignored

            if self.simu.detector.nsaturated_detpx == 0:
                mag_sat = mag
                break

        self.simu.update(ABmag=origin_mag) # go back to original magnitude
        if nmd is not None:
            self.simu.update(nmd=origin_nmd)

        return mag_sat  # last magnitude from the loop

    def get_saturation_stat(self, mags="9:17:0.1", nmd=(16,16,0),
                            lbda_range=[4000,6800], frame="obs", **kwargs):
        """
        Generate a dataframe with saturation information.

        :param mags: observed magnitudes to scan; if string, argument to `np.r_`
        :param tuple nmd: detector NMD parameters
        :param lbda_range: (wmin, wmax) test wavelength range [Å] (or list of)
        :param str frame: wavelength frame ('obs' or 'rest')
        :param kwargs: goes to get_band_snr

        :return: dataframe (index mags)
        """

        if type(mags) is str:
            mags = eval(f"np.r_[{mags}]")

        input_nmd = self.simu.get_parameter("nmd") # store input nmd
        self.simu.update(nmd=nmd, **kwargs)        # set the simulation nmd

        mag_info = []
        for mag in mags:
            self.simu.update(ABmag=mag)
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                snr = self.simu.get_band_snr(lbda_range, frame=frame)

            mag_info.append({"mag":mag,
                            "snr": snr,
                            "nsaturated_detpx": self.simu.detector.nsaturated_detpx,
                            "nsaturated_specpx": self.simu.detector.nsaturated_specpx,
                            })

        self.simu.update(nmd=input_nmd)             # set back the input

        # mag_info as list then set_index simplify labeling of index
        data = pandas.DataFrame(mag_info).set_index("mag")
        return data

    @staticmethod
    def plot_variancescan(df, savefile=None, timekey="obstime",
                         studied=["spatial_sigma", "spatial_scale", "ron", "dark"]):
        """
        static plotting method for results of scan_variance

        :param df: dataframe as created by :meth:`scan_variance()`
        :param str savefile: figure filename
        :param str timekey:
        :return: output figure
        """

        # Figure
        import matplotlib.pyplot as plt
        from matplotlib.colors import to_rgba

        fig = plt.figure(figsize=[12, 8])
        lmain, wmain = 0.2, 0.5

        ax = fig.add_axes([lmain, 0.1, wmain, 0.8])

        l_snr = wmain+lmain+0.04
        w_snr = 0.02
        axsnr = fig.add_axes([l_snr, 0.1, w_snr, 0.8])
        axvar = fig.add_axes([l_snr+w_snr, 0.1, 0.15, 0.8])

        height = 2
        spany = 0.5

        yticks = df.index * (spany+height)

        left = np.zeros(len(df))
        scanned = df.columns[df.columns.str.startswith("frac_")]

        total = np.sum(df[scanned], axis=1)
        cmap = plt.get_cmap('coolwarm_r')
        colors =  cmap(np.linspace(0.15, 0.85, len(scanned)))

        for i, k in enumerate(scanned):
            value = df[k] / total
            ax.barh(yticks, value, left=left, height=height, color=colors[i],
                   label=k.replace("frac_", ""))
            for y_, x_, l_ in zip(yticks, value, left):
                if x_ > 0.15:
                    ax.text(x_/2.+l_, y_, f"{x_*100:.0f}%",
                            va='center', ha="center", fontsize="small", color="w",
                            weight="bold")
            left = df[scanned[:i+1]].sum(axis=1)/ total

        # snr bar
        snr_color = to_rgba("0.6",0.4)
        axsnr.barh(yticks, df["snr"], height=height, color=snr_color)
        axsnr.invert_xaxis()

        # exptime bar
        exptime_color = "0.6"
        axvar.barh(yticks, df[timekey] / 3600, height=height, color=exptime_color)
        for i in range(len(df)):
            axvar.text(df.iloc[i][timekey] / 3600, yticks[i],
                       f" {df.iloc[i][timekey] / 60:.0f}'",
                       color="0.6", va="center", ha="left")

        ax.set_xlim(0, 1)
        axvar.set_ylim(*ax.get_ylim())
        axvar.set_xlim(0)

        for ax_ in fig.axes:
            clearwhich = ["left", "right", "top", "bottom"]
            for which in clearwhich:
                ax_.spines[which].set_visible(False)

        # Labeling bars
        wcenter = 9
        yticklabels = (
            df[studied].apply(lambda x:
                              f'{x["spatial_sigma"]*1e3:^{wcenter}.0f}|' +
                              f'{x["spatial_scale"]*1e3:^{wcenter}.0f}|' +
                              f'{x["ron"]:^{wcenter}.0f}|' +
                              f'{x["dark"]*1e2:^{wcenter}.1f}',
                              axis=1)
            .values)

        ax.set_yticks(yticks, labels=yticklabels)
        ax.text(-0.01, 1.021,
                f"{'psf':^{wcenter}s}|{'spx':^{wcenter}s}|"
                f"{'ron':^{wcenter}s}|{'dark':^{wcenter}s}",
                transform=ax.transAxes,
                ha="right", va="bottom")

        ax.text(-0.01, 1.018, '×100'.center(wcenter),
                transform=ax.transAxes, fontsize="small",
                ha="right", va="top")

        # xlabels
        ax.set_xlabel("Percent of Variance", loc="left", fontsize="large")
        axvar.set_xlabel(f" {timekey} [h]", loc="center", fontsize="large")
        axsnr.set_xlabel("S/N ", loc="right", fontsize="small", color=snr_color)
        axsnr.tick_params("x", labelsize="small",
                          color=snr_color, labelcolor=snr_color)

        # ticks
        snr_tick = np.round(df["snr"].mean(),-1)
        axsnr.set_xticks([snr_tick])
        axsnr.axvline(snr_tick, color="w", lw=2)
        ax.set_xticklabels([f"{x*100:.0f}%" for x in ax.get_xticks()])
        axvar.set_yticks([])
        axsnr.set_yticks([])

        # Legend
        ax.legend(bbox_to_anchor=(0., 1.02, 1., .102), loc='lower left',
                              ncol=len(scanned), mode="expand", borderaxespad=0.)

        # Show 20 min, 40 min, 1 h
        axvar.axvline(1/3, color="w", ls=":")
        axvar.axvline(2/3, color="w", ls="--")
        axvar.axvline(1, color="w", ls="-")
        if savefile:
            fig.savefig(savefile)

        return fig

    def show_saturation_mla(self, mag=None, ax=None, nmd=None, figsize=5,
                                cmap="cividis", **kwargs):
        """
        Display the saturation on the mla.

        :param float mag: locally change the observed magnitude
        :param ax: matplotlib's axes
        :param list nmd: locally change (n, m, d)
        :param float figsize: height of the figure. width automatically adapted.
        :param cmap: entry for plt.get_cmap()
        :param kwargs: goes to ax.imshow()
        :return: figure
        """

        # Things to change.
        if mag is not None:
            origin_mag = self.simu.get_parameter("ABmag")
            self.simu.update(ABmag=mag)
        else:
            origin_mag = None
            mag = self.simu.get_parameter("ABmag")

        if nmd is not None:
            origin_nmd = self.simu.get_parameter("nmd")
            self.simu.update(nmd=nmd)
        else:
            origin_nmd = None
            nmd = self.simu.get_parameter("nmd")

        # Cube
        data, variance = self.simu.get_detected_cube() # variance ignored
        f_saturated_pixels = np.sum(np.isnan(data), axis=0)/data.shape[0]

        # Plot
        if ax is None:
            import matplotlib.pyplot as plt
            fig = plt.figure(figsize=[figsize,figsize*0.7/0.8])
            ax = fig.add_axes([0.1,0.1,0.7,0.8])
            cax = fig.add_axes([0.82,0.1,0.02,0.8])
        else:
            fig = ax.figure
            cax = None

        # Actual plotting
        sc = ax.imshow(f_saturated_pixels, cmap=cmap, origin="lower",
                        **kwargs)
        cbar = fig.colorbar(sc, cax=cax, ax=ax)

        cbar.set_label("fraction of staturated pixel")
        ax.set_yticks(np.arange(data.shape[1])-0.5)
        ax.set_xticks(np.arange(data.shape[2])-0.5)

        ax.set_yticklabels(["" for _ in ax.get_yticks()])
        ax.set_xticklabels(["" for _ in ax.get_xticks()])
        ax.grid(lw=0.5)
        ax.text(0,1, f"magnitude: {mag} | readout-mode: {nmd}", transform=ax.transAxes,
                    va="bottom", ha="left", color="0.5")

        # Switch back to original.
        if origin_nmd is not None:
            self.simu.update(nmd=origin_nmd)

        if origin_mag is not None:
            self.simu.update(ABmag=origin_mag)

        return fig

    def show_saturation_stat(self, ax=None,
                             mags="9:17:0.1",
                             nmd_list=[(3,1,0), (16,1,0), (16,16,0)],
                             colors=["tab:blue","tab:orange", "0.7"]):
        """
        Show saturation statistics.

        (uses the :meth:`get_saturation_stat`` method)

        :param mags: observed magnitudes to scan; if string, argument to `np.r_`
        :param list nmd: list of detector NMD parameters
        :param list colors: list of matplotlib colors
        :return: figure
        """

        if ax is None:
            import matplotlib.pyplot as plt
            fig = plt.figure(figsize=[7,4])
            ax = fig.add_axes([0.1,0.15,0.8,0.75])
        else:
            fig = ax.figure

        # dataframe to be shown
        datas = [self.get_saturation_stat(mags, nmd) for nmd in nmd_list]

        # loop over the staturation dataframes
        for i,(data, color, nmd) in enumerate(zip(datas, colors, nmd_list)):
            ax.scatter(data.index, data["nsaturated_detpx"],
                        c=color, vmin=0, marker="s",
                        label='detecter pixels' if i==0 else None)
            ax.scatter(data.index, data["nsaturated_specpx"],
                        c=color, vmin=0, marker=".",
                        edgecolor="w", lw=0.5,
                        label='spectral pixels' if i==0 else None)

            min_notstat = data[data["nsaturated_detpx"]==0].index.min()
            # provide the saturation limit info and nmd color.
            ax.axvline(min_notstat, color=color, lw=0.5)
            ax.text(min_notstat+0.01, 1.5, f"{min_notstat:.1f} mag \n {nmd}",
                    fontsize="small", color=color,
                    rotation=90, ha="center", va="bottom")

        ax.set_yscale("log")
        ax.set_ylim(1, 1e5) # hard coded, bad.

        # fancy top legend
        ax.legend(bbox_to_anchor=(0., 1.02, 1., .102), loc='lower left',
                  ncol=2, mode="expand", borderaxespad=0.,
                  frameon=False,  fontsize="small")

        # labels.
        ax.set_xlabel("star magnitude", fontsize="large")
        ax.set_ylabel("number of pixels", fontsize="large")

        return fig


class StudySample(Study):

    def __init__(self, simu, data):
        """
        Study a sample.

        :param Simulation simu: simulation to be explored.
        :param DataFrame data: target data
        """

        super().__init__(simu=simu)
        self.data = data

    @classmethod
    def from_config(cls, config, size=5_000, **kwargs):
        """
        Load the sample given its config.

        This call `Simulation.from_config(config)`.

        :param dict config: top level configuration containing
                            configurations for scene, spectrograph, detector
                            and extraction parameters (by default:
                            use default config from
                            :func:`mlaperf.iotools.get_config`)
        :param int size: number of targets in the sample
        :param kwargs: goes to get_sneia_simulation (zmax, zmin, etc)
        :return: sample instance
        """

        from .simulation import Simulation
        simu = Simulation.from_config(config)
        data = get_sneia_simulation(size=size, **kwargs)
        return cls(simu=simu, data=data)

    def load_nramp(self, target_snr=10, force_reload=False, **kwargs):
        """
        update self.data with nramp parameters (using compute_nramp)

        :param float target_snr: objective SNR
        :param bool force_reload: is self.data already has nramp, shall the re-measure it ?
        :param kwargs: goes to the compute_nramp() method (zbins, use_dask etc)
        """

        if "nramp" in self.data and not force_reload:
            warnings("nramp already loaded. Set force_reload to true to reload")

        if "nramp" in self.data:
            _ = self.data.pop("nramp") # clean out
        self.data = self.compute_nramp(self.data, target_snr=10, **kwargs)

    def compute_nramp(self, data, target_snr=10,
                      zbins="0.001:1.5001:31j",
                      cbins="-0.3:0.5:9j",
                      x1bins="-4:4:9j",
                      use_dask=False, **kwargs
                     ):
        """
        Computes the nramp for each data row.

        :param DataFrame data: dataframe with columns 'z', 'c' and 'x1'.
        :param float target_snr: objective SNR
        :param zbins: redshift bining ; if string set `np.r_` otherwise array.
        :param cbins: color bining ; if string set `np.r_` otherwise array.
        :param x1bins: string bining ; if string set `np.r_` otherwise array.
        :param bool use_dask: shall this use dask (Client must be process based)
        :param kwargs: goes to fetch_nramp, update the simulation parameters.
        :return: copy of input data with additional bin and nramp columns.
        """

        if not np.all(np.in1d(["z","c","x1"],data.columns)):
            raise AttributeError("data must contain at least 'z','c' and 'x1'")

        data_ = data.copy()
        # binning
        if type(zbins) is str:
            zbins = eval(f"np.r_[{zbins}]")
        if type(cbins) is str:
            cbins = eval(f"np.r_[{cbins}]")
        if type(x1bins) is str:
            x1bins = eval(f"np.r_[{x1bins}]")

        z_bin = pandas.cut(data["z"], zbins, labels=np.arange(len(zbins[1:])))
        c_bin = pandas.cut(data["c"], cbins, labels=np.arange(len(cbins[1:])))
        x1_bin = pandas.cut(data["x1"], x1bins, labels=np.arange(len(x1bins[1:])))

        # format zbin_cbin_x1bin
        data_["bin"] = z_bin.astype("str")+"_"+c_bin.astype("str")+"_"+x1_bin.astype("str")
        binned = data_.groupby("bin")[["z", "c","x1"]].mean()

        # list of kwargs | rename as simu uses redshift not "z"
        updates = [d_.to_dict() for i, d_ in binned.rename({"z":"redshift"}, axis=1).iterrows()]

        if use_dask:
            import dask
            d_nramps = dask.delayed(list)([dask.delayed(self.fetch_nramp)(target_snr, **{**kwargs,**update_})
                                          for update_ in updates])
            nramps = d_nramps.compute() # list trick avoid requiring client as input
        else:
            nramps = [self.fetch_nramp(target_snr, **{**kwargs,**update_})
                      for update_ in updates]
        # merge
        binned["nramp"] = nramps
        dataout = data_.merge(binned["nramp"].reset_index(), on="bin")
        return dataout

    def get_total_exptime(self, overhead=None, ftargets=None):
        """
        compute the total observing time required (in sec)

        :param float overhead: extra time per target
        :param float ftargets: (0->1) fraction of brightest targets to observe
        :return float: total exposure time needed (in sec).
        """

        target_on_target = self.data["nramp"] * self.simu.detector.exposure_time
        # only take the brightest targets
        if ftargets is not None:
            target_on_target = target_on_target.sort_values()
            target_on_target = target_on_target.iloc[:int(len(target_on_target)*ftargets)]

        # extra time spent per target
        if overhead is not None:
            target_on_target +=overhead

        return target_on_target.sum()

    def scan_totaltime(self, zbins="0.001:1.5001:21j", cbins="-0.3:0.5:7j", x1bins="-4:4:7j",
                       highlight_ftargets=0.05, overhead=1000, use_dask=False,
                       **kwargs):
        """
        scan the total exposure time needed for this sample.

        :param zbins: redshift bining ; if string set `np.r_` otherwise array.
        :param cbins: color bining ; if string set `np.r_` otherwise array.
        :param x1bins: string bining ; if string set `np.r_` otherwise array.
        :param float highlight_ftargets: calcul the times needed for the top X percent.
        :param float overhead: observation overhead per target.
        :param kwargs: simulation parameter to scan {name:list, }
        :return: dataframe

        """

        df_params = mesh_kwargs(**kwargs)
        updates = [s_.to_dict() for i, s_ in df_params.iterrows()]
        orig = self.simu.get_parameter( list(kwargs.keys()) )
        dataout = []
        for update in updates:
            _ = self.update_simulation(**update)
            self.load_nramp(use_dask=use_dask, force_reload=True,
                           zbins=zbins, cbins=cbins, x1bins=x1bins)
            d_ = {"targets": self.get_total_exptime(),
                  "targets_main": self.get_total_exptime(ftargets=1-highlight_ftargets),
                  "targets_overhead":  self.get_total_exptime(overhead)
                 }
            dataout.append(d_)

        self.simu.update(**orig)
        return df_params.join(pandas.DataFrame(dataout))

    def show_hubblediagram_nramp(self, vmax=None, hcolor="tab:grey", cstep=1):
        """
        Show the sample hubble diagram colored by the number of ramps

        :param DataFrame data: dataframe containing at least magobs, z and nramp
        :para int vmax: upper limit for the colormap
        :param hcolor: matplotlib color's of the histograms
        :param int cstep: step of the colormap
        :param int min_ramp: minimal number of ramp bins for the colormap
        :return: figure
        """

        import matplotlib.pyplot as plt
        from matplotlib.colors import to_rgba

        data = self.data
        nramp = data["nramp"]

        fig = plt.figure(figsize=[7,5])

        left, bottom, width, height = 0.12, 0.12, 0.65, 0.65
        spanx, spany = 0, 0
        top, right = 0.05, 0.05
        height_t = 1-(bottom+height+spany+top)
        width_r = 1-(left+width+spanx+right)

        ax = fig.add_axes([left, bottom, width, height])
        axr = fig.add_axes([left+width+spanx, bottom, width_r, height])
        axt = fig.add_axes([left, bottom+height+spany, width, height_t])
        cax = fig.add_axes([left+width*0.5, bottom+0.05, width*0.3, 0.02])
        #
        # Scatter
        #
        if vmax is None:
            vmax = np.max(nramp)

        cmap = plt.get_cmap("coolwarm", vmax)
        sc = ax.scatter(data["z"], data["magobs"],
                       s=5, lw=0, c=data["nramp"], cmap=cmap, vmax=vmax+1)
        cbar = fig.colorbar(sc, cax=cax, orientation="horizontal")
        cbar.set_ticks( np.arange(1,vmax+1, step=cstep)+0.5,
                      labels=np.arange(1,vmax+1, step=cstep))
        #
        # histogram
        #
        prop = dict(bins="auto", histtype="step", fill=True,
                       lw=1, facecolor=to_rgba(hcolor,0.3),
                        edgecolor=to_rgba(hcolor,0.8))
        axt.hist(data["z"], orientation='vertical',
                **prop)
        axr.hist(data["magobs"], orientation='horizontal',
                **prop)

        #
        # Axes, ticks etc.
        #
        ax.set_ylim(17, 29)
        axt.set_xlim(*ax.get_xlim())
        axt.set_xticklabels(["" for _ in axt.get_xticks()])

        axr.set_ylim(*ax.get_ylim())
        axr.set_yticklabels(["" for _ in axr.get_yticks()])

        clearwhich = ["left","right","top"] # "bottom"
        [axt.spines[which].set_visible(False) for which in clearwhich]
        axt.tick_params(axis="y", labelsize="small",
                       labelcolor="0.7", color="0.7")


        clearwhich = ["bottom","right","top"]
        [axr.spines[which].set_visible(False) for which in clearwhich]
        axr.tick_params(axis="x", labelsize="small",
                       labelcolor="0.7", color="0.7")

        # Labels
        ax.set_xlabel("Redshift", fontsize="large")
        ax.set_ylabel("Magnitude (restframe-B)", fontsize="large")
        cax.set_title("n-ramp", fontsize="small")

        return fig

    def show_targets_obstime(self, ax=None, color="C0", second_color="w",
                          target_fractions=[20,50, 80,90,95,99,100]):
        """
        Shows how many targets can be observed as a function of the fraction
        of total time.

        the 'nramp' parameter should be loaded. See load_nramp

        :param ax: matplolib's axes
        :param color: main figure color (matplotlib color)
        :param second_color: color of the line and text with the axes
        :param list target_fractions: fraction of target displayed
        :return: figure
        """

        import matplotlib.pyplot as plt
        from matplotlib.colors import to_rgba
        from astropy import units

        time_on_target = (self.data["nramp"] *
                          self.simu.detector.exposure_time).sort_values()

        if ax is None:
            fig = plt.figure(figsize=[6,4])
            ax = fig.add_axes([0.1,0.1,0.8,0.8])
        else:
            fig = ax.figure

        total = time_on_target.sum() # in second
        cumsum = time_on_target.cumsum().values / total


        ftargets = np.asarray(target_fractions)/100
        ftimes = np.percentile(cumsum, ftargets*100)

        ax.fill_between(np.linspace(0,1, len(time_on_target)), cumsum,
                        facecolor=to_rgba(color,0.9),
                        edgecolor=to_rgba(color,1), lw=2)
        prop = dict(lw=0.5)
        ax.hlines(ftimes, 0, ftargets, color=color, **prop)
        ax.vlines(ftargets, 0, ftimes, color=second_color, **prop)

        # Target labels
        [ax.text(t_, 0.01, f"{t_:.0%}",
                 rotation=90, color=second_color, fontsize="x-small",
                va="bottom", ha="right")
         for t_ in ftargets[:-1]]

        ax.text(1.01, 0, f"{len(time_on_target)} targets", rotation=90,
                va="bottom", ha="left", color=color,
                transform=ax.transAxes, weight="medium")

        # Tile labels
        [ax.text(0.01,f_, f"{f_:.0%}",
                 rotation=0, color=color, fontsize="x-small",
                va="bottom", ha="left")
         for f_ in ftimes]

        total_in_week = total * units.second.to("week")
        ax.text(1., 1., f"{total_in_week:.1f} weeks", rotation=0,
                va="bottom", ha="right", color=color,
                transform=ax.transAxes, weight="medium")

        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)

        clearwhich = ["left","right","top","bottom"]
        [ax.spines[which].set_visible(False) for which in clearwhich]
        ax.set_xticks([])
        ax.set_yticks([])

        ax.set_ylabel("Fraction of on-target time", fontsize="large")
        ax.set_xlabel("Fraction of targets", fontsize="large")
        return fig

    def show_timescan(self, data=None, ax=None, scanning={}, **kwargs):
        """
        Display the dataframe created by :meth:`scan_totaltime`.

        :param DataFrame data: dataframe generated by :meth:`scan_totaltime`.
            If `None`, this will automatically measure on given the
            scanning parameters.
        :param ax: matplotlib's ax
        :param dict scanning: if data is not given, this is the scanning properties.
        """

        if data is None:
            data = self.scan_totaltime(**scanning)

        return show_timescan(data, ax=ax, **kwargs)


if __name__ == "__main__":

    from mlaperf import iotools
    import matplotlib.pyplot as plt

    config = iotools.get_config()
    study = Study.from_config(config)

    # Scan variance for these parameters
    df = study.scan_variance(
        target_snr=10, lbda_range=[4000, 6800],
        free_param="nramp",
        spatial_sigma=np.asarray([20, 40, 60])*1e-3,
        ron=[10],
        dark= [1e-2],
        spatial_scale=np.asarray([20, 40, 60])*1e-3)

    # Select things that last less than 2h and sort
    data = (df[df["obstime"] < 2*3600]
            .sort_values(["obstime","snr"],ascending=[True, False])
            .reset_index())

    fig = study.plot_variancescan(data)
    plt.show()
